#+TITLE: Emacs Configuration
#+AUTHOR: Daan van Berkel
#+EMAIL: daan.v.berkel.1980@gmail.com

* Tabs
Show tabs with a width of two.
#+BEGIN_SRC emacs-lisp
(setq tab-width 2)
#+END_SRC

The tab stop should occur at intervals of two.
#+BEGIN_SRC emacs-lisp
(setq tab-stop-list (number-sequence 2 200 2))
#+END_SRC

We do not want Emacs to insert real tabs, let it use spaces instead.
#+BEGIN_SRC emacs-lisp
(setq indent-tabs-mode nil)
#+END_SRC
* Autosave & Backup
** Autosave
I do not like the autosave functionality. Work loss is an
indication that you should commit more often.
#+BEGIN_SRC emacs-lisp
(setq auto-save-default nil)
#+END_SRC

** Backup
I am also not fond of default backup behaviour. Although the backup
behaviour is very customizable, (see for example
[[http://www.emacswiki.org/emacs/BackupDirectory]]) for now I will shut
it down.
#+BEGIN_SRC emacs-lisp
(setq backup-inhibited t)
#+END_SRC

* Hooks
** Before Save Hooks
I personally do not like trailing whitespaces so I am adding a save
hook that takes care of that problem.

#+BEGIN_SRC emacs-lisp
(add-hook 'before-save-hook 'delete-trailing-whitespace)
#+END_SRC
* Themes
In order to experiment with themes the following commands are usefull.
1. M-x load-theme. Loads a preloaded theme. Tab-completion is provided.
2. M-x disable-theme. Reverts back to the default theme.

I like a darker theme, specificially tango-dark, that comes pre-installed.
#+BEGIN_SRC emacs-lisp
(load-theme 'tango-dark t)
#+END_SRC
* Org Mode
** Babel
We would like to evaluate various code block so we specify the
corresponding =org-babel-load-languages= option.

#+BEGIN_SRC emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)
   (js . t)
   (perl . t)
   (python . t)
   (ruby . t)
   (sh . t)
  ))
#+END_SRC

* Requires
** Line Numbers
We use the excellent linum library for line numbers.
#+BEGIN_SRC emacs-lisp
(require 'linum)
#+END_SRC

I like line numbers to show up in my buffers at all times.
#+BEGIN_SRC emacs-lisp
(global-linum-mode t)
#+END_SRC
